# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-17 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20170316_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('txt', models.TextField()),
                ('created_by_name', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('src', models.TextField(blank=True)),
                ('question_id', models.IntegerField()),
                ('tweet_infos', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('txt', models.TextField()),
                ('created_by_name', models.CharField(blank=True, max_length=30, null=True)),
                ('created_by_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('src', models.CharField(blank=True, max_length=30, null=True)),
                ('tweet_infos', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
