# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-17 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20170317_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='txt_clean',
            field=models.TextField(blank=True, null=True),
        ),
    ]
