# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-01 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_answer_txt_clean'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
